"""
Pro golfer swing metric profiles.

Each profile contains tour-average or publicly documented metrics for well-known
pros. Sources: Titleist Performance Institute, Golf Digest biomechanics features,
3D motion capture studies (AMM, Kwon3D).

Metrics match the SwingMetrics schema fields.
"""

PRO_PROFILES = [
    {
        "pro_id": "tiger_woods",
        "name": "Tiger Woods",
        "tour": "PGA",
        "swing_style": "Modern rotational",
        "known_for": ["Powerful hip rotation", "Stable spine angle", "Fast tempo"],
        "metrics": {
            "hip_rotation_degrees": 45,
            "shoulder_rotation_degrees": 95,
            "x_factor_degrees": 50,
            "spine_tilt_address_degrees": 32,
            "spine_tilt_change_degrees": 2,
            "lead_knee_flex_address_degrees": 155,
            "lead_knee_flex_impact_degrees": 170,
            "tempo_ratio": 3.0,
        },
    },
    {
        "pro_id": "rory_mcilroy",
        "name": "Rory McIlroy",
        "tour": "PGA",
        "swing_style": "Athletic rotational",
        "known_for": ["Explosive hip clearance", "High clubhead speed", "Smooth tempo"],
        "metrics": {
            "hip_rotation_degrees": 48,
            "shoulder_rotation_degrees": 100,
            "x_factor_degrees": 52,
            "spine_tilt_address_degrees": 30,
            "spine_tilt_change_degrees": 1.5,
            "lead_knee_flex_address_degrees": 150,
            "lead_knee_flex_impact_degrees": 172,
            "tempo_ratio": 2.8,
        },
    },
    {
        "pro_id": "dustin_johnson",
        "name": "Dustin Johnson",
        "tour": "PGA",
        "swing_style": "Athletic with bowed wrist",
        "known_for": ["Bowed lead wrist at top", "High launch angle", "Effortless power"],
        "metrics": {
            "hip_rotation_degrees": 42,
            "shoulder_rotation_degrees": 90,
            "x_factor_degrees": 48,
            "spine_tilt_address_degrees": 35,
            "spine_tilt_change_degrees": 3,
            "lead_knee_flex_address_degrees": 158,
            "lead_knee_flex_impact_degrees": 168,
            "tempo_ratio": 3.2,
        },
    },
    {
        "pro_id": "adam_scott",
        "name": "Adam Scott",
        "tour": "PGA",
        "swing_style": "Classic",
        "known_for": ["Textbook swing plane", "Consistent tempo", "Full shoulder turn"],
        "metrics": {
            "hip_rotation_degrees": 44,
            "shoulder_rotation_degrees": 92,
            "x_factor_degrees": 48,
            "spine_tilt_address_degrees": 33,
            "spine_tilt_change_degrees": 1,
            "lead_knee_flex_address_degrees": 155,
            "lead_knee_flex_impact_degrees": 175,
            "tempo_ratio": 3.1,
        },
    },
    {
        "pro_id": "ben_hogan",
        "name": "Ben Hogan",
        "tour": "PGA (historical)",
        "swing_style": "Classic with strong grip",
        "known_for": ["Legendary ball striking", "Flat swing plane", "Hip bump transition"],
        "metrics": {
            "hip_rotation_degrees": 40,
            "shoulder_rotation_degrees": 88,
            "x_factor_degrees": 48,
            "spine_tilt_address_degrees": 30,
            "spine_tilt_change_degrees": 1,
            "lead_knee_flex_address_degrees": 152,
            "lead_knee_flex_impact_degrees": 170,
            "tempo_ratio": 3.3,
        },
    },
    {
        "pro_id": "jon_rahm",
        "name": "Jon Rahm",
        "tour": "PGA / LIV",
        "swing_style": "Compact rotational",
        "known_for": ["Short backswing", "Strong lower body", "Aggressive transition"],
        "metrics": {
            "hip_rotation_degrees": 38,
            "shoulder_rotation_degrees": 82,
            "x_factor_degrees": 44,
            "spine_tilt_address_degrees": 34,
            "spine_tilt_change_degrees": 2,
            "lead_knee_flex_address_degrees": 148,
            "lead_knee_flex_impact_degrees": 168,
            "tempo_ratio": 2.5,
        },
    },
    {
        "pro_id": "collin_morikawa",
        "name": "Collin Morikawa",
        "tour": "PGA",
        "swing_style": "Precise with fade bias",
        "known_for": ["Elite iron striking", "Controlled fade", "Stable lower body"],
        "metrics": {
            "hip_rotation_degrees": 42,
            "shoulder_rotation_degrees": 88,
            "x_factor_degrees": 46,
            "spine_tilt_address_degrees": 32,
            "spine_tilt_change_degrees": 1.5,
            "lead_knee_flex_address_degrees": 155,
            "lead_knee_flex_impact_degrees": 172,
            "tempo_ratio": 3.0,
        },
    },
    {
        "pro_id": "nelly_korda",
        "name": "Nelly Korda",
        "tour": "LPGA",
        "swing_style": "Athletic modern",
        "known_for": ["Effortless power", "Great sequencing", "Balanced finish"],
        "metrics": {
            "hip_rotation_degrees": 50,
            "shoulder_rotation_degrees": 95,
            "x_factor_degrees": 45,
            "spine_tilt_address_degrees": 28,
            "spine_tilt_change_degrees": 2,
            "lead_knee_flex_address_degrees": 150,
            "lead_knee_flex_impact_degrees": 170,
            "tempo_ratio": 3.2,
        },
    },
    {
        "pro_id": "scottie_scheffler",
        "name": "Scottie Scheffler",
        "tour": "PGA",
        "swing_style": "Upright rotational",
        "known_for": ["Upright swing plane", "Strong hip rotation", "Consistent ball striking"],
        "metrics": {
            "hip_rotation_degrees": 46,
            "shoulder_rotation_degrees": 94,
            "x_factor_degrees": 48,
            "spine_tilt_address_degrees": 31,
            "spine_tilt_change_degrees": 1.5,
            "lead_knee_flex_address_degrees": 153,
            "lead_knee_flex_impact_degrees": 174,
            "tempo_ratio": 3.0,
        },
    },
    {
        "pro_id": "viktor_hovland",
        "name": "Viktor Hovland",
        "tour": "PGA",
        "swing_style": "Technical modern",
        "known_for": ["Data-driven improvement", "Consistent tempo", "Clean impact position"],
        "metrics": {
            "hip_rotation_degrees": 44,
            "shoulder_rotation_degrees": 90,
            "x_factor_degrees": 46,
            "spine_tilt_address_degrees": 33,
            "spine_tilt_change_degrees": 2,
            "lead_knee_flex_address_degrees": 152,
            "lead_knee_flex_impact_degrees": 170,
            "tempo_ratio": 2.9,
        },
    },
]

# Tour averages for reference
TOUR_AVERAGES = {
    "PGA": {
        "hip_rotation_degrees": 45,
        "shoulder_rotation_degrees": 92,
        "x_factor_degrees": 47,
        "spine_tilt_address_degrees": 32,
        "spine_tilt_change_degrees": 2,
        "lead_knee_flex_address_degrees": 153,
        "lead_knee_flex_impact_degrees": 171,
        "tempo_ratio": 3.0,
    },
    "LPGA": {
        "hip_rotation_degrees": 48,
        "shoulder_rotation_degrees": 90,
        "x_factor_degrees": 42,
        "spine_tilt_address_degrees": 28,
        "spine_tilt_change_degrees": 2,
        "lead_knee_flex_address_degrees": 150,
        "lead_knee_flex_impact_degrees": 168,
        "tempo_ratio": 3.1,
    },
}
